### ISSUE TITLE
사진 삽입 기능

### ISSUE THREAD

**Issue by benkim077** [benkim077/benkim077.github.io#22]

**Comment by benkim077** [comment]
css 설정 
img 바로 뒤에 em이 오는 경우를 나타내는 선택자
```css
img + em { 
  display: block;
  text-align: center;
}
```

md 파일 작성
img 바로 뒤에 italic을 넣으면 캡션으로 이용할 수 있다.
```md
![image](/src/assets/image-name.png)*이 곳에 캡션을 입력하세요.*
```
